### ISSUE TITLE
Random Crash due to null-pointer in FlangerBerryVine.BERRY

### ISSUE THREAD

**Issue by quiqueck** [bunten2005/enderscape#13] opened 2022-07-03 13:34 UTC
I just had a random crash with Enderscape 0.3.3 and the latest dev-build of BCLib:
```
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2248.method_9564()" because "net.bunten.enderscape.blocks.FlangerBerryVine.BERRY" is null
	at net.bunten.enderscape.blocks.FlangerBerryVine.method_9652(FlangerBerryVine.java:144) ~[enderscape-0.3.3-1.19.jar:?]
	at net.bunten.enderscape.blocks.FlangerBerryVine.method_9514(FlangerBerryVine.java:118) ~[enderscape-0.3.3-1.19.jar:?]
	at net.minecraft.class_4970$class_4971.method_26199(class_4970.java:947) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.redirect$ddf000$redirectBlockStateTick(class_3218.java:9731) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18203(class_3218.java:495) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_14161(class_3215.java:379) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:323) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:318) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[client-intermediary.jar:?]
	... 5 more
```

As far as I can tell, it is not related to changes in BCLib, but please let me know if you think that the upcoming update did break things for you.

**Comment by bunten2005** [comment] 2022-07-03 19:11
Duplicate of #12 and fixed in 8e9af7d28407a341d8211e5c78adc1bfc5796f3f. v0.3.4 will be released later on with these fixes.

**Closed by bunten2005** 2022-07-03 19:11 UTC
Labels: bug, 1.19, fixed
